{% set data = load_setup_py_data() %}

package:
  name: plotwidgets
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/plotwidgets.git

build:
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # your library dependencies
    - python
    - ipython
    - ipywidgets 
    - seaborn
    - matplotlib
    - jupyterlab>=4
    - nodejs

channels:    # your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify
  
test:
  imports:
    - plotwidgets
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/plotwidgets.git
  license: MIT
  # summary: "Blah blah"
  # description: |
  #   "Blah blah"
  #   "Blah blah"
  dev_url: https://github.com/munch-group/plotwidgets.git
  doc_url: https://munch-group.org/plotwidgets
