project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package
    # - objects.txt
    # - objects-test.txt

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/      
    # quartodoc-test:
    #   url: https://machow.github.io/quartodoc
    #   inv: objects-test.txt

website:
  title: "libraryname"
  page-navigation: true
  navbar:
    left:
      # - file: examples/
      #   text: Examples
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/munch-group/libraryname/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/overview.qmd
        - section: "Basics"
          contents:
            - pages/basics.qmd
        - section: "Examples"
          contents:
            - pages/example.ipynb            
            - pages/something.ipynb            
        - section: "Advanced"
          contents:
            - pages/advanced.qmd
        - section: "Library reference"
          contents:
            - api/index.qmd

format:
  html:
    theme: cosmo
    css:
      - api/_styles-quartodoc.css
      - styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: api
  package: libraryname
  render_interlinks: true
  options:
    signature_name: full
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"

  sections:
    - title: Some section
      desc: ""
      contents:
        - foo        # function: quartodoc.get_object
        - bar.baz       # submodule func: quartodoc.ast.preview
