project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    ipython:
      url: https://ipython.readthedocs.io/en/stable/          

website:
  title: "plotwidgets"
  page-navigation: true
  navbar:
    left:
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/munch-group/plotwidgets/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/getting_started.qmd
        - section: "Examples"
          contents:
            - examples/showcase.ipynb            
            - examples/widgets.ipynb            
        - section: "Library reference"
          contents:
            - api/index.qmd

format:
  html:
    theme: cosmo
    css:
      - api/_styles-quartodoc.css
      - styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: api
  package: plotwidgets
  render_interlinks: true
  options:
    signature_name: full
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"

  sections:
    - title: Some section
      desc: ""
      contents:
        - seaborn

